language: python

os:
  - linux

python:
    - 3.3
    - 3.4
    - 3.5

install:
    - pip install asyncio
    - python setup.py install

script:
    - python runtests.py
    - PYTHONASYNCIODEBUG=1 python runtests.py
