environment:
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

build: false

test_script:
  - "%PYTHON%\\python.exe runtests.py -v"
